---
- name: add the newrelic repo key
  apt_key: url="https://download.newrelic.com/548C16BF.gpg" state=present

- name: add newrelic repo
  apt_repository:
    repo: "deb http://apt.newrelic.com/debian/ newrelic non-free"
    state: present

- name: install newrelic system monitoring
  apt: pkg=newrelic-sysmond state=latest

- name: configure newrelic system monitoring
  template: src=nrsysmond.cfg
            dest=/etc/newrelic/nrsysmond.cfg
            owner=newrelic
            group=newrelic
            mode=0440

- name: ensure that newrelic is running
  service: name=newrelic-sysmond state=started
